# Generated by Django 4.1.4 on 2023-01-18 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
